version: "3"
services:
  db:
    image: postgres:9-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: family-tree-dev
    volumes:
      - db-data:/var/lib/postgresql/data
  
  api:
    image: family-tree-api
    ports:
      - 4000:4000

volumes:
  db-data:
    driver: local
